server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    initialization-mode: always
    continue-on-error: true
  banner:
    location: classpath:hogwarts-banner.txt
datasets:
  rooms:
    - number: 1
      house: GRYFFINDOR
    - number: 2
      house: HUFFLEPUFF
    - number: 3
      house: RAVENCLAW
  students:
    - name: "Harry Potter"
      pet: OWL
    - name: "Ron Weasley"
      pet: RAT
    - name: "Hermine Granger"
      pet: CAT
    - name: "Draco Malfoy"
      pet: RAT
  ingredients:
    - name: "Unicorn hair"
    - name: "Venomous Tentacula"
    - name: "Mandrake"
    - name: "Shrivelfig"
    - name: "Fluxweed"
    - name: "Horklump Juice"
    - name: "Dittany"
    - name: "Alcohol"
    - name: "Frog brain"
    - name: "Beetle"
    - name: "Griffin claw"
    - name: "Knotgrass"
    - name: "Mushroom"
  recipes:
    - name: "Strength"
    - name: "Healing"
  potions:
    - name: "Strength Potion"
