spring:
  banner:
    location: classpath:hogwarts-banner.txt
datasets:
  rooms:
    - number: 1
      house: GRYFFINDOR
    - number: 2
      house: HUFFLEPUFF
    - number: 3
      house: RAVENCLAW
    - number: 4
      house: SLYTHERIN
